spring:
  # mysql
  datasource:
    my_db:
      jdbc-url: jdbc:mysql://localhost:3306/mydb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

testConfig: abc